server:
  port: 9901

spring:
  data:
    mongodb:
      host: localhost
      database: chat-user
      port: 27017
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: b26dffa8c04846ff8ba9b89bc07483e8
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
#            redirect-uri: 'localhost:3000'
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
          naver:
            client-name: Naver
            client-id: jVo_SVZWPKEyJmQjqK4W
            client-secret: sJkHASTjKZ
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"          # (== http://localhost:80/login/oauth2/code/naver) 게이트에이 하드코딩방식
            authorization-grant-type: authorization_code
            scope: name, email
          google:
            client-name: google
            client-id: 129842654485-c84i13kt2mj4kghbq25kbn4t2kdjh97b.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize    #카카오 login Page
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   #naver login Page
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    secretKey: 1234-1234-1234-1234-1234
    expiration: 1800000